### ISSUE TITLE
test_periodogram fails with lowlevel scipy.signal.lombscargle error

### ISSUE THREAD

**Issue by sspagnol** [wesleybowman/UTide#101]
If I run the tests (python 3.9.7, scipy 1.7.1) have a failure from test_periodogram.py with error messages like

```
TypeError: Invalid call to pythranized function `_lombscargle(float64[:], float64[:] (reshaped), float64[:])'
```

Using comment in https://github.com/scipy/scipy/issues/14420, in periodogram.py modified parameters passed to signal.lombscargle to

```
    xr = np.real(x)
    xr = np.asarray(xr, dtype=float, order='C')
    xr = np.ndarray(xr.shape, dtype=float, buffer=xr)
    # signal.lombscargle returns "(A**2) * N/4 for a harmonic signal
    # with amplitude A for sufficiently large N."
    # It takes *angular* frequencies as 3rd argument.
    freq_radian = freq * 2 * np.pi
    psdnorm = 2 * delta_t * n / (w ** 2).sum()
    out.Pxx = psdnorm * signal.lombscargle(t, xr, freq_radian)

    if x.dtype.kind == "f":
        return out
    xi = x.imag
    xi = np.asarray(xi, dtype=float, order='C')
    xi = np.ndarray(xi.shape, dtype=float, buffer=xi)
    out.Pyy = psdnorm * signal.lombscargle(t, xi, freq_radian)
```

Don't know if there a smarter way to achieve this, and once (if?) scipy.signal + pythran interaction gets sorted assume the xr/xi rewrite won't be needed.

**Comment by efiring** [comment]
I turns out that we still get a failure with scipy 1.7.3 because the second argument is a view.
I submitted an issue to scipy: https://github.com/scipy/scipy/issues/15964
