### ISSUE TITLE
Convert to python3

### ISSUE THREAD

**Issue by ocefpaf** [wesleybowman/UTide#11]
- [ ] Convert to python3

**Comment by wesleybowman** [comment]
For this, we would definitely want to have support for both 2 and 3, since a large majority of the scientific community uses 2, including some people already using this version of UTide for their projects.

**Comment by ocefpaf** [comment]
Sure!  Both python veersions should be supported to allow a smooth transition.

Here are the options I know:
1. `six`
2. "common syntax" between py2.7` and `py3`
3. automatic conversion using `2to3`.

I used 3 before but, even though it is the easiest/fastest way, it is a bad choice in the long run because we just delay a real conversion to python3.

In my experience 2 works better: it reduces the burden on the maintainers and keep the code base unified in one syntax.  The down side is that python <= 2.7 (sometimes 2.6 is OK) will not be supported.

Anyways, if support for python < 2.7 is needed, [six](http://pythonhosted.org//six/) is the best option.

**Comment by wesleybowman** [comment]
I wouldn't think below 2.7 would be needed. If we go too much support then it makes it near impossible to maintain for everything.

**Comment by ocefpaf** [comment]
Great!  if the goal is 2.7 and up  I will cook up another PR soon.

**Comment by ocefpaf** [comment]
@wesleybowman Before I start let me know how you feel about PR #9.  To avoid merge conflicts in the future.
