### ISSUE TITLE
Error in Finding coefficient

### ISSUE THREAD

**Issue by Diljit123** [wesleybowman/UTide#111]
![image](https://user-images.githubusercontent.com/51814537/167553439-b9e21616-bd07-4d12-8896-1baf1a66a952.png)

I am getting this error while running thr utide code in Jupyter. The tidal heights are returned as zero values. How can it be solved.

**Comment by Diljit123** [comment]
![image](https://user-images.githubusercontent.com/51814537/167579702-cc081cee-de3f-452a-b4b6-c857a2d1b331.png)

DT_hour is an array of python datenum values from the date_rng hourly.

**Comment by efiring** [comment]
What versions of utide and matplotlib are you running?

**Comment by Diljit123** [comment]
I am using utide version 0.3.0 and matplotlib version 3.5.2.

**Comment by efiring** [comment]
Good, all up to date!  Try using your date_rng_hourly as the time array for solve and reconstruct.  With 0.3.0 that is supposed to work.  Also with this version, use of a datenum array should work *if* you provide the correct "epoch" keyword argument.  Matplotlib changed its default epoch some time back, so it no longer matches the utide default, hence the need to include the keyword argument.  With the DT_hour you have, you would need `epoch="1970-01-01"`.  The epoch is needed only when time is input as a datenum array.

**Comment by Diljit123** [comment]
Thank you for the solution. This worked.
