### ISSUE TITLE
Problem with version 0.3.0, Python 3.10 and Ubuntu 22.04

### ISSUE THREAD

**Issue by pgr123** [wesleybowman/UTide#113]
Good morning,
I tried my old program with the new version 0.3.0 under Python 3.10 and I cannot make it work 
When I try 
from utide import solve,reconstruct
I get the error `
Traceback (most recent call last):

  File "/tmp/ipykernel_3117/1389739857.py", line 1, in <module>
    from utide import solve,reconstruct

  File "/home/pascal/.local/lib/python3.10/site-packages/utide/__init__.py", line 3, in <module>
    from ._solve import solve

  File "/home/pascal/.local/lib/python3.10/site-packages/utide/_solve.py", line 9, in <module>
    from .harmonics import ut_E

  File "/home/pascal/.local/lib/python3.10/site-packages/utide/harmonics.py", line 11, in <module>
    from ._ut_constants import ut_constants

  File "/home/pascal/.local/lib/python3.10/site-packages/utide/_ut_constants.py", line 13, in <module>
    ut_constants = loadbunch(_ut_constants_fname, masked=False)

  File "/home/pascal/.local/lib/python3.10/site-packages/utide/utilities.py", line 288, in loadbunch
    out[k] = _structured_to_bunch(xx[k], masked=masked)

  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 254, in __getitem__
    return format.read_array(bytes,

  File "/usr/lib/python3/dist-packages/numpy/lib/format.py", line 743, in read_array
    raise ValueError("Object arrays cannot be loaded when "

ValueError: Object arrays cannot be loaded when allow_pickle=False

```
Do you know why and what can I do ?
Thank you.
Good year.

Pascal

**Comment by efiring** [comment]
Pascal, what is the version of numpy you are using?
Using utide 0.3.0 from conda-forge in a Python 3.10 environment,
with numpy 1.23.5, I can't reproduce the problem.

**Comment by efiring** [comment]
Also, I just now tried to reproduce this on ubuntu 22.04, with
```
pip3 install --user utide
```
It works, no problem. But this is with the Ubuntu 22.04
python, which is 3.8.
I'm guessing your problem is that you are pulling in numpy from
the system python 3.8, and utide from your local python 3.10.

**Comment by pgr123** [comment]
Thank you for your answers but I have Ubuntu 22.04.1 and the default version of Python is 3.10.6-1~22.04 and not 3.8.
I have updated numpy to version 1.24.1 and try all what you suggest but that does not work.
It seems that utide is not compatible with Python 3.10.
(It works well with Ubuntu 20.04.5 and Python 3.8.10)
What can I do, please. I love utide and I hope I can continue to use it.
Thank you.
Have a good day.

**Comment by efiring** [comment]
You are at least partly correct: I was confused about the ubuntu version on the other machine I tried.
But the problem is not python 3.10 itself, because I have tried that, and Python 3.10 is part of the
test matrix for Utide on github.  Under these circumstances, the natural presumption is that there
is something odd about your installation.

I think there are clues in your traceback, e.g.:
```
File "/home/pascal/.local/lib/python3.10/site-packages/utide/utilities.py", line 288, in loadbunch
out[k] = _structured_to_bunch(xx[k], masked=masked)
```
For Utide 0.3.0, this is line 298, not 288.  So it seems that what you have installed somehow is
not what it is supposed to be. You can verify this: https://github.com/wesleybowman/UTide/blame/v0.3.0/utide/utilities.py.

In general I recommend the use of miniconda, with a minimal base environment, and one or more
named working environments.  This makes it easy to keep things updated, and to try different
versions of packages fully isolated in their own environments, without disturbing a primary
working environment.

**Comment by pgr123** [comment]
Thank you, but I am sorry, I verified the code and the code I use (which is installed) is the same as utilities.py and the error 'structured_to_bunch' is well on line 298 but it seems to refer to line 288 : 
out = Bunch()
So I think that the problem is well reported ! And not solved !
Thank you for your help.

**Comment by ocefpaf** [comment]
> So I think that the problem is well reported ! And not solved !

Not really. Can you please provide:

- how did you install your Python?
- are you using any sort of environment isolation?
- `pip freeze` from the environment you are calling utide?

I just tested on the same Ubuntu with the system Python, creating a python 3.10 environment with pyenv, and everything works.

**Comment by pgr123** [comment]
Thank you.
I don't install Python, it is installed by Ubuntu. I use Python 3.10.6 which is the default with Ubuntu 22.04.
I don't use any environment isolation.
I did not create special environment : I made as usual pip3 install utide and/or sudo pip3 install utide.

**Comment by pgr123** [comment]
And excuse my very bad english, please.

**Comment by pgr123** [comment]
Congratulations to efiring and ocefpaf for your responsiveness.

**Comment by pgr123** [comment]
Here is the result of pip freeze :
[pip freeze.txt](https://github.com/wesleybowman/UTide/files/10398810/pip.freeze.txt)

Also, When I try the test_solve.py (in the directory tests of UTide-0.3.0), I get the result :
/usr/local/lib/python3.10/dist-packages/utide/harmonics.py:16: RuntimeWarning: invalid value encountered in cast
  nshallow = np.ma.masked_invalid(const.nshallow).astype(int)
/usr/local/lib/python3.10/dist-packages/utide/harmonics.py:17: RuntimeWarning: invalid value encountered in cast
  ishallow = np.ma.masked_invalid(const.ishallow).astype(int) - 1

I don't understand where is the problem and how to solve it. I try on 3 differents computers.
Thank you

**Comment by pgr123** [comment]
Thank you.
I think I understand where is the problem : how can I access the name, A, g of the coefficients after a call to coef=solve(d,h,...
My program uses coef['A'][i] but that does not work with the new version and in Spyder if I see coef, there is A but nothing in.
I use 
```
print( "Onde\tA\tA_ci\tg\tg_ci")
print( "Z0\t%g" %(coef['mean']))   #This seems to work
for i in range(len(coef['name'])):    #But not that
    print( "%s\t%g\t%g\t%g\t%g" %(coef['name'][i],coef['A'][i],coef['A_ci'][i],coef['g'][i],coef['g_ci'][i]))
```
but that does not work ! Why ?
So, where is the problem with that new version ?
Thank you very much for your help.
Pascal

**Comment by pgr123** [comment]
WHen I run my program, I get absurd results for A, g, ... and I have the warnings :
```
/usr/local/lib/python3.10/dist-packages/utide/periodogram.py:342: RuntimeWarning: divide by zero encountered in scalar divide
  fs = 1 / dt  # sampling frequency: cycles (samples) per hour
/usr/local/lib/python3.10/dist-packages/utide/periodogram.py:344: RuntimeWarning: divide by zero encountered in divide
  allfrq = np.arange(nt // 2 + 1) / (nt * dt)
/usr/local/lib/python3.10/dist-packages/utide/periodogram.py:344: RuntimeWarning: invalid value encountered in divide
  allfrq = np.arange(nt // 2 + 1) / (nt * dt)
/usr/local/lib/python3.10/dist-packages/utide/periodogram.py:77: RuntimeWarning: invalid value encountered in cast
  i_constit = np.round(np.interp(cfreq, freq, indices)).astype(int)
```
In my data, the interval of time is da[1]-da[0]=0.0069444444961845875 (that is ten minutes).

What is the problem in periodogram.py ?

**Comment by pgr123** [comment]
I think that I solve my problem. I have to add epoch='matlab' in the opts !
Thank you very much and excuse me.

**Comment by pgr123** [comment]
But is there a doc for the new version ?
Because I did not know the parameter epoch.
It seems that now whe can have the dates as a datetime and we are not obligated to have the date in matlab datenum format.
Is this true ?

**Comment by efiring** [comment]
Yes.  See the docstring for solve.  Here is the top part:
```
Signature: utide.solve(t, u, v=None, lat=None, **opts)
Docstring:
Calculate amplitude, phase, confidence intervals of tidal constituents.

Parameters
----------
t : array_like
    Time in days since `epoch`, or np.datetime64 array, or pandas datetime array.
u : array_like
    Sea-surface height, velocity component, etc.
v : {None, array_like}, optional
    If `u` is a velocity component, `v` is the orthogonal component.
lat : float, required
    Latitude in degrees.
epoch : {string, `datetime.date`, `datetime.datetime`}, if datenum is provided in t.
    Default `None` if `t` is `datetime`, `np.datetime64`, or `pd.datetime array.`
    Optional valid strings are
        - 'python' : if `t` is days since '0000-12-31'
        - 'matlab' : if `t` is days since '0000-00-00'
    Or, an arbitrary date in the form 'YYYY-MM-DD'.

```

**Comment by pgr123** [comment]
Solved !
Thank you for your help !
Good week-end.
