### ISSUE TITLE
Utide with dask

### ISSUE THREAD

**Issue by yadidya-b** [wesleybowman/UTide#120]
Hi

I was wondering if it's possible to use utide for multidimensional dask arrays. 
Or if it is in the pipeline to achieve it some day?

It would be really cool to use utide for large datasets instead of single time series. 

Thanks.

**Comment by ocefpaf** [comment]
You can wrap it as a `delayed` with dask. See this example:

https://gist.github.com/rsignell-usgs/28c6044f9c35b7ff84320736d3e1252c

PS: This is a use case question so I'm closing it b/c there is no actionable items for the developers.
