### ISSUE TITLE
Pythonic naming: remove all the 'ut_' prefixes

### ISSUE THREAD

**Issue by efiring** [wesleybowman/UTide#13]
@wesleybowman Would you support a PR to simplify the naming by removing all use of "ut_"?  The module would then be used as
```python
import utide as ut
...
coefs = ut.solve(...)
```
This is how we are handling the TEOS-10 gsw module.

**Comment by ocefpaf** [comment]
:+1:

**Comment by wesleybowman** [comment]
This sounds great. Looks more pythonic as well.

**Comment by efiring** [comment]
#15 addresses enough of this that I think we can close the issue.
