### ISSUE TITLE
lmbscgc & lmbscga in progress

### ISSUE THREAD

**Issue by iflament** [wesleybowman/UTide#16]
Hi! A short message to notify everyone that I am working on the lmbscgc & lmbscga functions (to avoid work overlap).

**Comment by ocefpaf** [comment]
@iflament I am not sure [this code](https://github.com/ocefpaf/python-ssa-mtm/blob/master/lomb_periodogram.py) is helpful.  It is a Matlab code translation that I used in the past.


Good luck!  Lookinf forward to `lmbscgc` and `lmbscga` :wink:

**Comment by ocefpaf** [comment]
@efiring and @iflament I am not sure if this algorithm is adequate for Utide, but I think it is worth taking a look:

http://www.astroml.org/gatspy/

There is also a blog post about it [here](https://jakevdp.github.io/blog/2015/06/13/lomb-scargle-in-python/).

**Comment by efiring** [comment]
@ocefpaf We have already taken care of the L-S algorithms.

**Comment by efiring** [comment]
@iflament I think you can close this.  I can't.

**Comment by ocefpaf** [comment]
Thanks @efiring.
