### ISSUE TITLE
Datetime as input

### ISSUE THREAD

**Issue by saulomeirelles** [wesleybowman/UTide#2]
Hi all,

The numpy function "np.isnan" is incompatible with datetime. The following error is risen when using datetime:

...\utide\ut_slvinit.pyc in ut_slvinit(tin, uin, vin, **opts)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

 I would recommend to replace np.isnan with pd.isnull.

Greetings,

Saulo

**Comment by efiring** [comment]
@saulomeirelles To date, there has never been any intention of supporting an input array of datetime instances, whether generated by pandas or anything else.  Once #37 is in place, such support could be added, but I don't see it as the highest priority.  An array of datetime instances is a slow, bulky, and cumbersome way to specify a large number of times.  np.datetime64 is more efficient, but also trouble-prone and semi-broken, as a search of the numpy mailing list will show.

**Comment by saulomeirelles** [comment]
Good point. I did not realize that by that time.

**Comment by efiring** [comment]
Closing; I opened #88 as an updated version, since a lot has changed since this one was opened.
