### ISSUE TITLE
Variable default value should not be a list

### ISSUE THREAD

**Issue by ocefpaf** [wesleybowman/UTide#21]
We have two variables with a list as default value here:

https://github.com/wesleybowman/UTide/blob/master/utide/robustfit.py#L7

That is not recommended (See http://docs.python-guide.org/en/latest/writing/gotchas).

@wesleybowman Also, this function does not return anything and this module appears to incomplete.  I am removing it from the tests for now.  But we should add it again once it is done.

**Comment by wesleybowman** [comment]
Yeah, it is incomplete since I had hit a roadblock. I think @efiring is writing the correct one though? I am not sure.

**Comment by ocefpaf** [comment]
OK.  So it is safe to leave it out of the tests.  Thanks!
