### ISSUE TITLE
NaN output

### ISSUE THREAD

**Issue by saulomeirelles** [wesleybowman/UTide#3]
Hi all,

I compared the performance of the harmonic analysis for the same series using Matlab and Python. I ran "ut_solv" followed by "ut_reconstr" for u and v velocity components. In Matlab, the output was as expected but in Python I got just NaN's. It is hard to find out where the problem is because no errors popped up while running.

Any thoughts?

Cheers,

Saulo

**Comment by efiring** [comment]
@saulomeirelles or @wesleybowman I think this issue is obsolete and can be closed.
