### ISSUE TITLE
New release with latest master

### ISSUE THREAD

**Issue by ocefpaf** [wesleybowman/UTide#35]
@wesleybowman fixing #30 solves a problem for many people on Windows. Would you mind tagging a new release? Maybe also send it to PyPI?

**Comment by wesleybowman** [comment]
Yeah, I will try and get those done tonight

**Comment by ocefpaf** [comment]
Thanks @wesleybowman!

**Comment by wesleybowman** [comment]
@ocefpaf We are live on PyPI as well! [Here it is!](https://pypi.python.org/pypi/UTide/0.1.0)

**Comment by ocefpaf** [comment]
Awesome! Thanks for doing this @wesleybowman!!
