### ISSUE TITLE
Using UTide.reconstruct with other harmonic constituents.

### ISSUE THREAD

**Issue by pwcazenave** [wesleybowman/UTide#39]
For reasons with which I won't bore you, I'd like to use UTide to predict tidal elevations from another source of harmonic constituent amplitude and phases (namely the TPXO data).

For `reconstruct()`, I need to supply the `coef` `Bunch` with a number of keys. I've figured out what most of those are, but I'm a bit stuck on the confidence intervals. I don't think the TPXO data have confidence intervals for their values but UTide needs those. To what should I set them in their absence?

**Comment by efiring** [comment]
The confidence intervals are needed by `reconstruct` only if you want the constituents to be auto-selected based on a signal-to-noise ratio estimate.  If you are using TPXO, I suspect you don't want this, in which case you can bypass the code that accesses the confidence intervals by including an explicit constituent list as a 'cnstit'  kwarg to `reconstruct`.  (This is based on a quick look at the code; I don't have an example handy.)  The list would use the standard string name abbreviations (up to 4 characters).  I'm sorry I don't have an example ready to go.  Let us know whether this suggestion leads you to a solution.  If you can come up with a minimal working example, please pass it on, and we can include it as a test or an example.

**Comment by efiring** [comment]
Also, I may be able to make a simple modification that would make the use of the 'cnstit' kwarg unnecessary here. I will try to look at that some time during the next few days.  If you don't see a PR for it, send me a reminder.

**Comment by pwcazenave** [comment]
Thanks for the pointer.

I've changed my code to take the `constit` kwarg in `reconstruct` but got a key error:

```
reconstruct:Traceback (most recent call last):
  File "make_tides.py", line 273, in <module>
    noisy=noisy, constit=uconst)
  File "make_tides.py", line 96, in predict
    pred = reconstruct(times, coef, **kwargs)
  File "/home/pica/Code/UTide/utide/_reconstruct.py", line 38, in reconstruct
    u, v = _reconstr1(t, coef, epoch=epoch, verbose=verbose, **opts)
  File "/home/pica/Code/UTide/utide/_reconstruct.py", line 76, in _reconstr1
    SNR = (coef['A']**2)/((coef['A_ci']/1.96)**2)
KeyError: 'A_ci'
```

I set the intervals (amplitude and phase) to zero and it seems to work, but I'm not sure if that's a valid approach.

**Comment by efiring** [comment]
The code is presently looking for 'cnstit' here, not 'constit'.  (The API and internal code are still in an intermediate state, not fully pythonized.) 

I would expect setting the intervals to zero would give the correct result, but with numpy divide-by-zero warnings along the way.

**Comment by pwcazenave** [comment]
Ah, sorry! 

Yes, I get lots of divide by zero errors. I suppose checking whether the confidence intervals are zero before doing the calculation would do away with those but might also slow things down.

**Comment by efiring** [comment]
There are better ways to handle your use case, coming soon.

**Comment by pwcazenave** [comment]
Lovely. Thanks!

**Comment by efiring** [comment]
See #41. It should mean that you can leave the confidence intervals out entirely if you call `reconstruct(..., min_SNR=0)`, or if you supply a list of constituent names in a `constit` kwarg (with the 'o', no longer 'cnstit', and now documented.)  Testing is still minimal, however.

**Comment by efiring** [comment]
@pwcazenave Can this issue be closed now?

**Comment by pwcazenave** [comment]
Yes.

**Comment by naught101** [comment]
@pwcazenave: Did you manage to get the TPXO data working with UTide? A gist or similar script would be really useful, if you did. Would save me a lot of time figuring out what goes where :)

**Comment by naught101** [comment]
Ah, looks like there's some stuff in here: https://github.com/pwcazenave/PyFVCOM/blob/master/PyFVCOM/grid/_grid.py#L1157

**Comment by efiring** [comment]
If what you want is tide heights and velocities based on the TPXO models (but not including the version 8 with its mix of resolutions), see https://currents.soest.hawaii.edu/hgstage/pytide/.  It provides a very fast python interface to the models.  It includes Fortran extension code, so it can be compiled reasonably easily on OS X and Linux, but Windows is not supported.  Installation instructions and an example are included here: https://currents.soest.hawaii.edu/ocn_data_analysis/installation.html.

**Comment by naught101** [comment]
Oh, excellent, that's exactly what I want. Thank you!
