### ISSUE TITLE
Problem running utide

### ISSUE THREAD

**Issue by parkermac** [wesleybowman/UTide#44]
I'm trying to use your utide and can't get it to work.  I use python 3.6, anaconda distribution, and installed utide from the command line as "pip install utide"

I read in a year-long tidal time seriesand make t and z vectors that are standard one-dimensional ndarrays, but get the error messages below.  I figure the problem may be with my installation, or my python version, or my code, but I thought I would ask you first before I run down too many rabbit holes.

The function call was:
a = utide.solve(t, z, v=None,
             lat=49.337,
             nodal=False,
             trend=False,
             method='ols',
             conf_int='linear',
             Rayleigh_min=0.95)

Here are the error messages:

In [26]: run obs_plot_canada_utide.py
solve: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/Documents/ptools/tide/obs_plot_canada_utide.py in <module>()
     55              method='ols',
     56              conf_int='linear',
---> 57              Rayleigh_min=0.95)
     58 
     59 if False:

/Applications/anaconda/lib/python3.6/site-packages/utide/_solve.py in solve(t, u, v, lat, **opts)
    146     compat_opts = _translate_opts(newopts)
    147 
--> 148     coef = _solv1(t, u, v, lat, **compat_opts)
    149 
    150     return coef

/Applications/anaconda/lib/python3.6/site-packages/utide/_solve.py in _solv1(tin, uin, vin, lat, **opts)
    163     # opt['cnstit'] = cnstit
    164     nNR, nR, nI, cnstit, coef = ut_cnstitsel(tref, opt['rmin']/(24*lor),
--> 165                                              opt['cnstit'], opt['infer'])
    166 
    167     # a function we don't need

/Applications/anaconda/lib/python3.6/site-packages/utide/constituent_selection.py in ut_cnstitsel(tref, minres, incnstit, infer)
     42 
     43     ii = np.isfinite(const.ishallow)
---> 44     const.freq[~ii] = np.dot(const.doodson[~ii, :], ader) / 24
     45 
     46     for k in ii.nonzero()[0]:

TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions

**Comment by efiring** [comment]
I suspect this is a bug that we have fixed, and we need to do a tag-and-release.  
In the meantime, please try the master branch here.

**Comment by wesleybowman** [comment]
> we need to do a tag-and-release

Agreed. 32 commits on master since the last, and we haven't put new commits on in a while now.

@parkermac if you try master and it succeeds, please report back :+1:

**Comment by ocefpaf** [comment]
> Agreed. 32 commits on master since the last, and we haven't put new commits on in a while now.

I am :+1:  to always [RERO](https://en.wikipedia.org/wiki/Release_early,_release_often)

**Comment by parkermac** [comment]
Success!!  Instead of using "pip install utide" to get the code I cloned the repo and then did "python setup.py install" (as the instructions said I should.  Then my test code worked correctly.  I will let you know if the results look any different from the matlab version with the same input data.

**Comment by ocefpaf** [comment]
@parkermac note that `python setup.py install` is slowly being deprecated.
You can use: `pip install .` to install from the current directory or, if you want to get fancy,
`pip install git+https://github.com/wesleybowman/UTide.git` to install directly from the repo's `master` branch without cloning.

**Comment by parkermac** [comment]
Thanks for the tip.

**Comment by wesleybowman** [comment]
> I will let you know if the results look any different from the matlab version with the same input data.

@parkermac thanks! and thanks for the issue!

**Comment by wesleybowman** [comment]
@parkermac I am going to close this issue, but feel free to put your results here.
