### ISSUE TITLE
Update the README to include conda install instructions

### ISSUE THREAD

**Issue by wesleybowman** [wesleybowman/UTide#45]
We are a part of the condaforge, so we should make sure our users know they can use conda to install the package.

**Comment by wesleybowman** [comment]
I think we can go a little further than
> If you are using conda and will not be developing the code, you can install from the IOOS channel. See https://github.com/ioos/conda-recipes/wiki.

**Comment by ocefpaf** [comment]
Oh dear! We need to remove any reference to the IOOS channel ASAP! I'll send a PR.

It is not maintained for years since we migrated to `conda-forge`.

**Comment by wesleybowman** [comment]
I just checked, and right now through `conda-forge` we have exactly 
> 2048 total downloads

:tada: 

Link: https://anaconda.org/conda-forge/utide

**Comment by ocefpaf** [comment]
Sure. I don't really have a strong preference when it comes to badges but I think that at least the license badge is nice to have at the top of the REAME.
