### ISSUE TITLE
how to specify only calculate M2, S2, K1, O1

### ISSUE THREAD

**Issue by gdshen** [wesleybowman/UTide#64]
I am wondering how to specify to calculate only a small number tides, instead of many tides?

**Comment by efiring** [comment]
From the docstring for `solve()`, this describes the keyword argument you can use to specify the constituents you want to include in the solution:
```
    constit : {'auto', array_like}, optional
        List of strings with standard letter abbreviations of
        tidal constituents; or 'auto' to let the list be determined
        based on the time span.
```

**Comment by gdshen** [comment]
Thanks very much. This solves my problems.
