### ISSUE TITLE
Tidal constituents of absolute current velocities?

### ISSUE THREAD

**Issue by sstaehler** [wesleybowman/UTide#65]
I am having a dataset of noise on a geophysical ocean bottom station,
which is proportional to the absolute value of the bottom current.

I would like to extract tidal constituents from this dataset, however,
given that I do not have the current vector, but the absolute value,
this is not quite straightforward (as a rough guess, I would expect to
see peaks at twice the frequency, plus tons of overtones). Did you
foresee the option to work on absolute current velocities in utide or
would you have an idea on where to start adding this?

**Comment by efiring** [comment]
I think your expectation is correct: the tidal harmonic frequencies will be doubled, and there will be harmonics and sum and difference frequencies.  The first thing to do is a conventional spectral analysis to see what you actually have--how prominent are the main peaks, and how much spectral broadening is there.  
Then, you could use simple least-squares fitting or complex demodulation to estimate the amplitudes of the signals in the main peaks.
I don't think that modification of utide to do the least-squares part of this would make sense.

**Comment by efiring** [comment]
Closing as "answered"; I don't think there are any action items for us here.

**Comment by sstaehler** [comment]
Thanks for the initial answer. That was actually quite helpful to me and I should have written this in here!
