### ISSUE TITLE
Avoid reading `ut_constants.mat` multiple times

### ISSUE THREAD

**Issue by ocefpaf** [wesleybowman/UTide#7]
`ut_constants.mat` is loaded in `__init__.py` and then re-loaded several times throughout the module.

**Comment by efiring** [comment]
@ocefpaf, are you working on this one, or should I have a look at it?

**Comment by ocefpaf** [comment]
I am not working on this right now.  If you have some spare time please... (We could use some of your magic here.)

**Comment by efiring** [comment]
This is closed by #14.  I should have put that in the commit message so that it would happen automatically, but I didn't, so someone has to close it manually.  I can't.

**Comment by ocefpaf** [comment]
Thanks @efiring!
