### ISSUE TITLE
When using .reconstruct to predict tide it slowly decreases down to very large numbers

### ISSUE THREAD

**Issue by caiodu** [wesleybowman/UTide#72]
When I use .reconstrut to predict tides over the period of my real data, the predicted data on the time series slowly drifts down to very large numbers, does anybody had this issue ? I already verified the code and all the setups, tried numbers of examples but it never works, I am able to get good data to predict the tide for the exact time period of my real data, but when I extrapolate to time periods over its lenght it goes down, and if I go back in time to predict the numbers go way up, very weird.
Thank you

**Comment by efiring** [comment]
I suspect that what is happening is that the long-period constituents are being included in the fit, but they are actually picking up energy from non-tidal parts of your record. How long is your record, and what is the list of constituents you are fitting?  What arguments are you providing to `solve`?

**Comment by caiodu** [comment]
First thank you for your quick reply, well I've tried a whole bunch of different settings both on '.solve' and '.reconstruct', it is wierd that when I use t_tide I get pretty good results on predicting my tide, they match NOAA's prediction, but on U_tide I'm getting this weird pattern treding way down on future predictions and way up on past predictions, and it doesn't matter the size of my record, the prediction always goes good for the same lenght of my record, both future or past, but when I go over the lenght of my record it plays up that way I described. I'm using the default list of constituents, which I guess is all of the calculated by '.solve'. My last try for solve was the simplest way possible: "coef = solve(time, water, lat=40.81)"

**Comment by efiring** [comment]
Try `solve` with kwarg `trend=False`.  It defaults to True.

**Comment by caiodu** [comment]
> Try `solve` with kwarg `trend=False`. It defaults to True.

Good stuff mate, it worked here, flawless. Thank you very much
