### ISSUE TITLE
verbose not implemented

### ISSUE THREAD

**Issue by clive3** [wesleybowman/UTide#85]
Hello - I noticed that you have not taken the verbose value that I have set in the newopts. 

I have added the following line in my local version:

def _reconstruct(t, goodmask, coef, verbose, constit, min_SNR, min_PE):

    twodim = coef['aux']['opt']['twodim']
    verbose = coef['aux']['opt']['newopts']['verbose']

**Comment by efiring** [comment]
The 'verbose' argument is supplied directly as a keyword argument to `reconstruct`.  Why do you want to override that with a value from 'coef'? 
Ideally, it would not even be there; the design has only partly evolved from its Matlab heritage, and both the 'verbose' argument and the messy coef and various options structures reflect that.

**Comment by efiring** [comment]
I don't think there is anything we need to do here so I am closing this; feel free to reopen it if needed.

**Comment by clive3** [comment]
i agree but because i am using the product to reconstruct tides using a grid produced by Matlab with batch procerssing I am having to make a few local changes

thanks
