### ISSUE TITLE
warning with last version of numpy

### ISSUE THREAD

**Issue by ltestut** [wesleybowman/UTide#89]
When updating with the last numpy version '1.20.0rc2' I've got a error message from Utide
utide\harmonics.py:184: RuntimeWarning: invalid value encountered in fmod  np.fmod(V, 1, out=V)
 It is not critical yet, and it works, but in the futur ...

**Comment by efiring** [comment]
Was this triggered by the test suite?

**Comment by ltestut** [comment]
No it was not trigered by the test suite. I solve the issue when I downgrade numpy to version 1.19.5

**Comment by efiring** [comment]
Please supply a minimal but complete example that causes the warning to be generated.
