### ISSUE TITLE
utide.solve and utide.construct

### ISSUE THREAD

**Issue by JueLinYe** [wesleybowman/UTide#90]
Greetings! May I ask a question about utide.reconstruct? I have a 1-d data of sea level and I am trying to obtain the astronomical tide by using uTide. My code more or less looks like this. 
   
     time1=mdates.date2num(data.index.to_pydatetime())
        
        coef1=utide.solve(time1,data['SeaLevel'].values,
                          lat=lat1,
                          method='irls',
                          conf_int='MC',
                          nodal=True,#include satellite corrections to improve results
                          constit=harmNames
                          )
       
        harmNames_sorted=coef1.name
        tide_aux=utide.reconstruct(time1,coef1,constit=harmNames_sorted)

I am getting a time series, of the tide, that looks like it has much smaller frequency than the astromical tide obtained with Foreman. I see that, in my case, I get a frequency in radians/hour from utide.solve, but utide.reconstruct is using this frequency in cycle per hour (as I can see from the comments in the source code). Hence the smaller frequency.  I must have dropped some option somewhere. 

Thanks in advance,

Jue

**Comment by efiring** [comment]
Please supply a very minimal, but still complete, example that illustrates the question.  Also, look at tests/test_solve.py, which illustrates a round-trip in which the results of solve are used in reconstruct.

**Comment by JueLinYe** [comment]
Thank you so much for the prompt reply. I have been running test_solve.py and looking into my code and data. I think that the technical problem is mine, and it does not seem to do with utide, for now. I have some issues with SA and SSA, but I will ask again if I am sure that there is something that I could contribute to utide.

Best regards,

Jue
