### ISSUE TITLE
Trying to reorder constituents as in ‘OrderCnstit’ 

### ISSUE THREAD

**Issue by aaretxabaleta-usgs** [wesleybowman/UTide#91]
As @rsignell-usgs mentioned in a previous issue, we are trying to analyze the tides at each grid cell in a numerical model solution. We run utide for each grid point but the order of the constituents can be different for each grid point. In the Matlab code, there is the option ‘OrderCnstit’ that allows passing a specified order of constituents when constit is not set to 'auto'. Is there a similar reordering for the python version?

**Comment by efiring** [comment]
Yes, there are some options that have not yet had their names pythonized and added to the docstring, and this is one.  It's all lower case: "ordercnstit", and it can be None, "frq", "snr", or a list of constituent names like ["M2", "S2"].

However... if I were doing this calculation for numerical model output, I would not use UTide directly; I would just extract and vectorize the underlying least-squares calculation, assuming all you want is the coefficients and possibly the series reconstructed from them.  Ideally, I would go ahead and package this vectorized short version as a separate function pair in UTide.  It's just among the many things I haven't gotten around to doing, like proceeding with more pythonization and cleanup of the codebase.

**Comment by ocefpaf** [comment]
@efiring I'm not sure we are really allowing that keyword. We have `strict=True` hardcoded in `Bunch` and that throws an error when an unexpected key is used. See https://github.com/wesleybowman/UTide/pull/93

**Comment by efiring** [comment]
OK, I will make a PR to add it properly.

**Comment by ocefpaf** [comment]
BTW, I'm moving our tests to GitHub Actions. PR soon... (Travis-CI has become unbearable for OSS projects lately.)

**Comment by efiring** [comment]
It turns out, with simple testing, that this ordering business opens up quite a rats' nest of interacting options and confusing code.  This may take some time to sort out.
